/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignments.scratch;

import org.junit.Test;

import assignments.scratch.cli.Schema;

import static org.junit.Assert.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class SchemaTest {
  @Test
  public void schemaMatchesSnapshot() throws IOException {
    Schema classUnderTest = new Schema();

    String schema = Files.readString(Paths.get("src/test/resources/schema.json"));
    assertEquals(classUnderTest.getSchema(), schema);
  }
}
